name: Docker image release

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  DOCKER_REPO_NAME: deepset/haystack

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: dummy
        run: exit 1
