name: Docker image release

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - 'v[0-9].[0-9]+.[0-9]+*'

env:
  DOCKER_REPO_NAME: deepset/haystack

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: dummy
        run: exit 0
