name: YAML Schema

on:
  workflow_dispatch: # Activate this workflow manually
  workflow_run:
    workflows:
      - Docker image release
    types:
      - completed

env:
  HAYSTACK_REF: ${{ github.event.workflow_run.head_branch || 'main' }}

jobs:

  run:
    if: ${{ !github.event.workflow_run || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      # Start a workflow in https://github.com/deepset-ai/haystack-json-schema
      # https://docs.github.com/en/rest/repos/repos#create-a-repository-dispatch-event
      - name: Dispatch to schemas repository with ref ${{ HAYSTACK_REF }}
        run: |
          curl \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.MY_TOKEN }}" \
          https://api.github.com/repos/askainet/haystack-json-schema/dispatches \
          -d '{"event_type":"generate-pipeline-schemas","client_payload":{"ref":"${{ env.HAYSTACK_REF }}"}}'
